// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zjU2YnkWmBOf_38mMZ8F-9oqZt9PcDE',
    appId: '1:634225843026:web:6b318cf8bfd17cd5f1788b',
    messagingSenderId: '634225843026',
    projectId: 'capsule-gsc-app',
    authDomain: 'capsule-gsc-app.firebaseapp.com',
    storageBucket: 'capsule-gsc-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByCPL6mO5-P_BXl6DgAb9qqQry6g3qDWM',
    appId: '1:634225843026:android:17ad095235ad46a3f1788b',
    messagingSenderId: '634225843026',
    projectId: 'capsule-gsc-app',
    storageBucket: 'capsule-gsc-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJkn3emwHmJfcxr6cN3Jpk2PvvzzkGZJs',
    appId: '1:634225843026:ios:48016045303d0903f1788b',
    messagingSenderId: '634225843026',
    projectId: 'capsule-gsc-app',
    storageBucket: 'capsule-gsc-app.appspot.com',
    iosBundleId: 'com.example.capsuleApp',
  );
}
